# Install SQLObject on windows and test against MS SQL server and postgres
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
# and Michael Sverdlik's appveyor-utils (https://github.com/cloudify-cosmo/appveyor-utils)
version: '{branch}-{build}'

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

services:
  - mysql
  - postgresql

environment:
  MYSQL_PWD: "Password12!"
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\run_with_env.cmd"

  matrix:
    - TESTS: "py27-mysql"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "2.7"
      PYTHON_HOME: "C:\\Python27"
      db: mssql2014

matrix:
  fast_finish: true

install:
  # Enable TCP for mssql
  # (from appveyor documentation)
  - ps: |
      [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Smo") | Out-Null
      [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement") | Out-Null
      $serverName = $env:COMPUTERNAME
      $instanceName = 'SQL2014'
      $smo = 'Microsoft.SqlServer.Management.Smo.'
      $wmi = new-object ($smo + 'Wmi.ManagedComputer')
      $uri = "ManagedComputer[@Name='$serverName']/ServerInstance[@Name='$instanceName']/ServerProtocol[@Name='Tcp']"
      $Tcp = $wmi.GetSmoObject($uri)
      $Tcp.IsEnabled = $true
      $TCP.alter()
      Set-Service SQLBrowser -StartupType Manual
      Start-Service SQLBrowser
      Start-Service "MSSQL`$$instanceName"
  # List ODBC drivers
  - ps: Get-OdbcDriver -Platform 32-bit | Select-Object -ExpandProperty Name
  - ps: Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin;C:\\Program Files\\PostgreSQL\\9.5\\bin;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade \"pip < 19.1\" setuptools"
  - "pip install --upgrade \"tox < 3.1\" ppu"
  - "pip --version"
  # List ODBC drivers
  - ps: Get-OdbcDriver -Platform 32-bit | Select-Object -ExpandProperty Name
  - ps: Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name

# Not a C project, so no build step
build: false

test_script:
  - "%CMD_IN_ENV% devscripts\\tox-select-envs %TESTS%"

after_test:
  - "remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache"
